app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("user/", include("users.urls")),
    path("vacancy/", include("vacancy.urls")),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users.views import UserLoginView, UserSingUpView, UserAccountView, UserProfileView, UserDetailView

urlpatterns = [
    path('login/', UserLoginView.as_view(next_page='/user/account/'), name='login'),
    path('singup/', UserSingUpView.as_view(), name='singup'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/user/login/'), name='logout'),

    path('account/', UserAccountView.as_view(), name='account'),
    path('profile/', UserProfileView.as_view(), name='profile'),

    path('details/<str:username>/', UserDetailView.as_view(), name='details'),
]

app/vacancy/urls.py
from django.urls import path, include
from vacancy.views import VacancyListView, VacancyDetailView

urlpatterns = [
    path('', VacancyListView.as_view(), name='vacancy_list'),
    path('detail/<slug:slug>/', VacancyDetailView.as_view(), name='vacancy_detail'),
]

app/vacancy/models.py
from django.db import models
from django.utils.text import slugify
from common.models import JobFormat, Skill
from users.choices import ENGLISH_LEVELS_CHOICES
from users.models import JobEmployerProfile

class Vacancy(models.Model):
    profile = models.ForeignKey(JobEmployerProfile, related_name='vacancy', on_delete=models.CASCADE, blank=True, null=True, verbose_name='Профіль роботодавця')
    slug = models.SlugField(unique=True, blank=True, verbose_name='Індитифікатор')
    title = models.CharField(max_length=100, blank=True, null=True, verbose_name='Заголовок')
    description = models.TextField(blank=True, null=True, verbose_name='Опис')
    english_level = models.CharField(max_length=64, choices=ENGLISH_LEVELS_CHOICES, default='no_english', blank=True,
                                     null=True, verbose_name='Рівень англійської')
    year_experience = models.PositiveIntegerField(default=0, blank=True, null=True, verbose_name='Років досвіду')
    job_format = models.ForeignKey(JobFormat, related_name='vacancy', on_delete=models.CASCADE,null=True, blank=True, verbose_name='Формат роботи')
    skills = models.ManyToManyField(Skill, related_name='vacancy', blank=True, verbose_name='Навички')
    salary = models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата')
    location = models.CharField(max_length=64, blank=True, null=True, verbose_name='Місто')
    is_active = models.BooleanField(default=True, verbose_name='Активна')
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True, verbose_name='Дата створення')
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True, verbose_name='Дата оновлення')

    class Meta:
        verbose_name = 'Вакансія'
        verbose_name_plural = 'Вакансії'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

app/vacancy/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from vacancy.models import Vacancy

class VacancyListView(ListView):
    model = Vacancy
    paginate_by = 10
    template_name = 'vacancy/vacancy_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'vacancy_count': Vacancy.objects.all().count()
        })
        return context

class VacancyDetailView(DetailView):
    model = Vacancy
    template_name = 'vacancy/vacancy_detail.html'

    def get_object(self, queryset=None):
        return get_object_or_404(self.model, slug=self.kwargs.get("slug"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        vacancy = self.get_object()

        context.update({
            "vacancy": vacancy,
            "title": f"Details for Vacancy",
            "page": "Details",})
        return context

app/templates/vacancy/vacancy_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% include 'banner_default.html' %}
<section class="site-section">
    <div class="container">
        <div class="row align-items-center mb-5">
            <div class="col-lg-8 mb-4 mb-lg-0">
                <div class="d-flex align-items-center">
                    <div>
                        <h2>{{ vacancy.title }}</h2>
                        <!--                <div>-->
                        <!--                  <span class="ml-0 mr-2 mb-2"><span class="icon-briefcase mr-2"></span>Puma</span>-->
                        <!--                  <span class="m-2"><span class="icon-room mr-2"></span>New York City</span>-->
                        <!--                  <span class="m-2"><span class="icon-clock-o mr-2"></span><span class="text-primary">Full Time</span></span>-->
                        <!--                </div>-->
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="row">
                    <div class="col-6">
                        <a href="#" class="btn btn-block btn-light btn-md"><span
                                class="icon-heart-o mr-2 text-danger"></span>Save Job</a>
                    </div>
                    <div class="col-6">
                        <a href="#" class="btn btn-block btn-primary btn-md">Apply Now</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8">
                <div class="mb-5">
                    <h3 class="h5 d-flex align-items-center mb-4 text-primary"><span
                            class="icon-align-left mr-3"></span>Job Description</h3>
                    <p>{{ vacancy.description }}</p>
                </div>
                <div class="mb-5">
                    <h3 class="h5 d-flex align-items-center mb-4 text-primary"><span
                            class="icon-align-left mr-3"></span>Skills</h3>
                    <p>
                        {% for skill in vacancy.skills.all %}
                        {{ skill.name }}
                        {% endfor %}
                    </p>
                </div>
                <div class="mb-5">
                    <h3 class="h5 d-flex align-items-center mb-4 text-primary"><span
                            class="icon-align-left mr-3"></span>Job Employer</h3>
                    <ul class="job-listings mb-5">
                        <li class="job-listing d-block d-sm-flex pb-3 pb-sm-0 align-items-center">
                            <a href="{% url 'details' vacancy.profile.user.username %}"></a>
                            <div class="job-listing-logo">
                                <img src="{{ vacancy.profile.get_logo_url }}" alt="Image" class="img-fluid">
                            </div>

                            <div class="job-listing-about d-sm-flex custom-width w-100 justify-content-between mx-4">
                                <div class="job-listing-position custom-width w-50 mb-3 mb-sm-0">
                                    <h2>{{ vacancy.profile.company_name }}</h2>
                                </div>
                                <div class="job-listing-location mb-3 mb-sm-0 custom-width w-25">
                                    <span class="icon-room"></span>
                                </div>
                                <div class="job-listing-meta">
                                    <span class="badge badge-success">Since {{ vacancy.profile.created_at.date.year }}</span>
                                </div>
                            </div>

                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="bg-light p-3 border rounded mb-4">
                    <h3 class="text-primary  mt-3 h5 pl-3 mb-3 ">${{ vacancy.salary }} / month</h3>
                    <ul class="list-unstyled pl-3 mb-0">
                        <li class="mb-2"><strong class="text-black">Location:</strong> {{ vacancy.location }}
                        </li>
                        <li class="mb-2"><strong class="text-black">Year experience:</strong> {{ vacancy.year_experience }}
                        </li>
                        <li class="mb-2"><strong class="text-black">English level:</strong> {{ vacancy.get_english_level_display }}
                        </li>
                        <li class="mb-2"><strong class="text-black">Format:</strong> {{ vacancy.job_format}}
                        </li>
                        <li class="mb-2"><strong class="text-black">Publication:</strong> {{ vacancy.created_at.date }}
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

app/templates/vacancy/vacancy_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% include 'banner_home.html' %}

<section class="py-5 bg-image overlay-primary fixed overlay" id="next"
         style="background-image: url('{% static 'images/hero_1.jpg' %}');">
    <div class="container">
        <div class="row mb-5 justify-content-center">
            <div class="col-md-7 text-center">
                <h2 class="section-title mb-2 text-white">JobBoard Site Stats</h2>
                <p class="lead text-white">Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita unde
                    officiis recusandae sequi excepturi corrupti.</p>
            </div>
        </div>
        <div class="row pb-0 block__19738 section-counter">

            <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
                <div class="d-flex align-items-center justify-content-center mb-2">
                    <strong class="number" data-number="1930">0</strong>
                </div>
                <span class="caption">Candidates</span>
            </div>

            <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
                <div class="d-flex align-items-center justify-content-center mb-2">
                    <strong class="number" data-number="54">0</strong>
                </div>
                <span class="caption">Jobs Posted</span>
            </div>

            <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
                <div class="d-flex align-items-center justify-content-center mb-2">
                    <strong class="number" data-number="120">0</strong>
                </div>
                <span class="caption">Jobs Filled</span>
            </div>

            <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
                <div class="d-flex align-items-center justify-content-center mb-2">
                    <strong class="number" data-number="550">0</strong>
                </div>
                <span class="caption">Companies</span>
            </div>


        </div>
    </div>
</section>

<section class="site-section">
    <div class="container">

        <div class="row mb-5 justify-content-center">
            <div class="col-md-7 text-center">
                <h2 class="section-title mb-2">{{ vacancy_count }} Job Listed</h2>
            </div>
        </div>

        <ul class="job-listings mb-5">
            {% for vacancy in object_list %}
            <li class="job-listing d-block d-sm-flex pb-3 pb-sm-0 align-items-center">
                <a href="{% url 'vacancy_detail' vacancy.slug %}"></a>

                <div class="job-listing-about d-sm-flex custom-width w-100 justify-content-between mx-4">
                    <div class="job-listing-position custom-width mb-3 mb-sm-0">
                        <h2 style="font-size: 24px;">{{ vacancy.title }}</h2>
                        <strong>{{ vacancy.description|truncatechars:250 }}</strong>

                    </div>
                    <div class="job-listing-meta">
                        {% if vacancy.is_active %}
                        <span class="badge badge-success">{{ vacancy.created_at.date }}</span>
                        {% else %}
                        <span class="badge badge-danger">{{ vacancy.created_at.date }}</span>
                        {% endif %}
                    </div>
                </div>

            </li>
            {% endfor %}
        </ul>
        <div class="row pagination-wrap">
            <div class="col-md-6 text-center text-md-left mb-4 mb-md-0">
                <span>Showing {{ object_list|length }} of {{ vacancy_count }} Vacancy</span>
            </div>
            <div class="col-md-6 text-center text-md-right">
                {% include 'pagination.html' %}
            </div>
        </div>


    </div>
</section>
{% if not user.is_authenticated %}
<section class="py-5 bg-image overlay-primary fixed overlay" style="background-image: url('images/hero_1.jpg');">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-8">
                <h2 class="text-white">Looking For A Job?</h2>
                <p class="mb-0 text-white lead">Lorem ipsum dolor sit amet consectetur adipisicing elit tempora adipisci
                    impedit.</p>
            </div>
            <div class="col-md-3 ml-auto">
                <a href="#" class="btn btn-warning btn-block btn-lg">Sign Up</a>
            </div>
        </div>
    </div>
</section>
{% endif %}

{% endblock %}